#!/bin/bash
sudo chown root:root node_modules/electron/dist/chrome-sandbox
sudo chmod 4755 node_modules/electron/dist/chrome-sandbox


sudo chown root:root  dist/linux-unpacked/chrome-sandbox
sudo chmod 4755  dist/linux-unpacked/chrome-sandbox

